### ISSUE TITLE
Console error with np, timer

### ISSUE THREAD

**Issue by openclipboard** [radjkarl/dataArtist#11]
Using console in Windows executable version (according to tutorial 4), we should be able to see np, timer, but this seems to be off.  

You can do regular Python things like 'import sys', so you can do:
print(sys.version)

but np isn't responding so well, nor is timer.

Result for 'np':
<module 'numpy' (<pyimod03_importers.FrozenImporter object at 0x0000000002798F28>)>

Result for 'timer':

    Traceback (most recent call last):
      File "pyqtgraph_karl\console\Console.py", line 159, in execSingle
      File "<string>", line 1, in <module>
    NameError: name 'timer' is not defined

**Comment by radjkarl** [comment]
Hi,

Thanks. Tutorial 4 is wrong. Must be depreciated - will correct that
Timer doesn't exists.
'timed' does. You can check out 'example_gameOfLife' for an exemplary use of the timed function

**Comment by openclipboard** [comment]
Alas, scripting on Windows and Ubuntu doesn't work, using 'example_gameOfLife'.

Traceback (most recent call last):
  File "dataArtist\widgets\Automation.py", line 574, in start
  File "<string>", line 9, in <module>
KeyError: 'Colorbar'

Other errors in mandelbrod_fast as well; using Windows, the following error occurs.  In Ubuntu, using pre-compiled version, existing screen expands to physical full screen size, and same error shows up.

Traceback (most recent call last):
  File "<string>", line 55, in update
  File "dataArtist\widgets\DisplayDock.py", line 357, in __setattr__
  File "dataArtist\widgets\DisplayDock.py", line 442, in removeLayer
  File "dataArtist\figures\plot\PlotWidget.py", line 143, in removeLayer
IndexError: pop from empty list

**Comment by radjkarl** [comment]
yeah i remember that error.
could you try it with the latest linux exec?
