### ISSUE TITLE
Right click Export fails - Windows and Linux

### ISSUE THREAD

**Issue by openclipboard** [radjkarl/dataArtist#12]
When in an image, right clicking gives the 'Export...' option.

When doing so in Windows:
Traceback (most recent call last):
  File "pyqtgraph_karl\GraphicsScene\GraphicsScene.py", line 534, in showExportDialog
  File "pyqtgraph_karl\GraphicsScene\exportDialog.py", line 30, in __init__
  File "pyqtgraph_karl\GraphicsScene\exportDialogTemplate_pyqt5.py", line 39, in setupUi
  File "pyqtgraph_karl\parametertree\ParameterTree.py", line 44, in __init__
  File "pyqtgraph_karl\parametertree\ParameterTree.py", line 86, in setParameters
  File "pyqtgraph_karl\parametertree\ParameterTree.py", line 103, in addParameters
AttributeError: 'ExportDialog' object has no attribute 'makeTreeItem'

Similar error in Linux.

**Comment by openclipboard** [comment]
Forward motion; Export popup shows up, but an error still is generated (Linux):

Traceback (most recent call last):
  File "/home/user/git/pyqtgraph/pyqtgraph_karl/GraphicsScene/exportDialog.py", line 132, in exportClicked
    self.currentExporter.export()
AttributeError: 'NoneType' object has no attribute 'export'
