### ISSUE TITLE
Scripting not operational; error thrown

### ISSUE THREAD

**Issue by openclipboard** [radjkarl/dataArtist#15]
For basic scripts like:

d.tools['Export'].param('Type').setValue('Txt file')

... errors occur (Windows and Linux)

Traceback (most recent call last):
  File "/home/user/git/dataArtist/dataArtist/widgets/Automation.py", line 574, in start
    exec(c, self._globals)
  File "<string>", line 1, in <module>
KeyError: 'Export'

Traceback (most recent call last):
  File "dataArtist\widgets\Automation.py", line 574, in start
  File "<string>", line 1, in <module>
KeyError: 'Export'

**Comment by radjkarl** [comment]
Ahh ... tool 'Export' was renamed into 'SaveToFile'
should work if you replace it.

Where did you find 
`d.tools['Export'].param('Type').setValue('Txt file')
`
i dont find it in the currect code any more...
