### ISSUE TITLE
FIT files not supported

### ISSUE THREAD

**Issue by willhobbs** [radjkarl/dataArtist#19]
I am trying to open .fit files, and I get the following error:

> Traceback (most recent call last):
  File "dataArtist\gui.py", line 434, in dropEvent
  File "dataArtist\widgets\Workspace.py", line 518, in addFiles
  File "dataArtist\widgets\Workspace.py", line 439, in addDisplay
  File "dataArtist\widgets\DisplayDock.py", line 103, in __init__
  File "dataArtist\input\getFileReader.py", line 25, in getFileReader
IOError: fit not supported

**Comment by radjkarl** [comment]
would you mind to send me a test image?

**Comment by radjkarl** [comment]
nice pic.

works in my version without any problems.
[image: Inline images 1]


can you wait a few months to have it fixed? i am restructuring that project
and will make some bigger changes, like adding some pro features
wont take too much time

**Comment by willhobbs** [comment]
What version are you using? I'm using the standalone Windows version. 

If there's a way to correct images without all calibrations (see my other issue submission), we would use this in the next month or so to process all of the EL images we have in a decent sized project.

Thanks. 

Will

**Comment by radjkarl** [comment]
Hi Will,

I am just uploaded a new version in which both issues should be resolved.
https://github.com/radjkarl/dataArtist/releases/tag/0.10.3

Not sure though - I am traveling and only sparsely on the PC.
If you still cannot open fits files, would you mind to install the win
redistributables:

https://www.microsoft.com/en-us/download/details.aspx?id=52685

Please let me know, whether it works after installing those.
In general I am not spending so much time on dataartist at the moment since
we have a new project which will correct, analyse and report on all
uploaded images automatically.
it should be released around may i guess.
dataArtist will soon be embedded in it as (optional) interactive image
processing solution  ...

cheers,
karl

**Comment by willhobbs** [comment]
Thanks for working on this! 

I'm getting a fatal error after installation ("failed to execute script gui_pyinstaller"):

![image](https://user-images.githubusercontent.com/19290886/33138436-1b088330-cf70-11e7-84bf-8aed5a976275.png)

I have the same issue with the 11/Oct version, but the 14/Jun version runs fine for me.

Will

**Comment by willhobbs** [comment]
I tried installing on a different Windows 10 PC, and i'm getting further, but still having issues. 

When opening an image, I get this warning:

> C:\Program Files (x86)\dataArtist\pyfits\util.py:893: UserWarning: Could not find appropriate MS Visual C Runtime library or library is corrupt/misconfigured; cannot determine whether your file object was opened in append mode.  Please consider using a file object opened in write mode instead.

I made sure to install both x64 and x86 redistributables.

Then when turning on the Calibrate toolbar, the lens distortion and flat field icons don't show up, and this appears:

> Traceback (most recent call last):
  File "dataArtist\widgets\Toolbars.py", line 217, in addTools
  File "dataArtist\figures\image\tools\calibrate\FlatField.py", line 33, in __init__
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "imgProcessor\camera\flatField\vignettingFromSpotAverage.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\skimage\filters\__init__.py", line 11, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\skimage\filters\thresholding.py", line 9, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\skimage\transform\__init__.py", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\skimage\transform\hough_transform.py", line 4, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
  File "skimage/transform/_hough_transform.pyx", line 13, in init skimage.transform._hough_transform (skimage\transform\_hough_transform.c:24794)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\skimage\draw\__init__.py", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\skimage\draw\draw.py", line 4, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\skimage\_shared\_geometry.py", line 4, in <module>
ModuleNotFoundError: No module named 'matplotlib'
ERROR loading toolbutton:  None
Traceback (most recent call last):
  File "dataArtist\widgets\Toolbars.py", line 217, in addTools
  File "dataArtist\figures\image\tools\calibrate\LensDistortion.py", line 36, in __init__
  File "dataArtist\figures\image\tools\calibrate\LensDistortion.py", line 21, in _import
ImportError: cannot import name 'EnoughImages'
ERROR loading toolbutton:  None

**Comment by radjkarl** [comment]
Ah crap,

This error can have multiple reasons ...
Thing is, I cannot reproduce it.
I assume you use a win7 PC, right?
I only have access to in win10 pcs, so i would like to ask you to install
https://github.com/radjkarl/dataArtist/releases/tag/0.10.3b

This version is identical to the last one but gives more output.

Please install and run dataartist in a command shell
-> cmd.exe
-> cd PATH/TO/DATAARTIST
-> dataArtist.exe

would you mind to send the all output generated?

**Comment by willhobbs** [comment]
Both PCs I'm using are Windows 10. 

On the first one (the PC that got the fatal error, Windows 10 Enterprise), I get this:

> c:\Program Files (x86)\dataArtist>dataArtist.exe
===== 2017.11.22 20:11:26 =====
Traceback (most recent call last):
  File "dataArtist\gui_pyinstaller.py", line 29, in <module>
  File "fancytools\os\windows\limitMemory.py", line 81, in decorated
  File "dataArtist\gui.py", line 610, in main
  File "dataArtist\gui.py", line 81, in __init__
  File "dataArtist\gui.py", line 296, in _appendMenubarAndPreferences
  File "dataArtist\widgets\preferences.py", line 290, in __init__
  File "dataArtist\widgets\preferences.py", line 238, in __init__
ValueError: tuple.index(x): x not in tuple
[11700] Failed to execute script gui_pyinstaller

One the second PC (Windows 10 Home), it opens fine but when opening an image and turning on the calibrate toolbar it gives me the same warnings/errors as I mentioned in the last comment.

Will

**Comment by radjkarl** [comment]
Hi Will,

Ah - that was helpful. Thanks.
All issues should be resolved - should. I am sure behind the surface of
resolved issues there is an army of even more ugly issues.
Would you mind to find out?
i replaced the exe in
https://github.com/radjkarl/dataArtist/releases/tag/0.10.3b

If starting sill doesn't work, please delete /win/users/<YOU>/.dataArtist


Cheers,
Karl

**Comment by willhobbs** [comment]
Karl,

It now opens fine on both of my Win 10 PCs, but when trying to run a manual Lens Distortion calibration, I get this error:

> Traceback (most recent call last):
  File "dataArtist\widgets\Tool.py", line 322, in toggle
  File "dataArtist\figures\image\tools\calibrate\LensDistortion.py", line 240, in activate
TypeError: calibrate() got an unexpected keyword argument 'max_images'

Will

**Comment by radjkarl** [comment]
Hi Will,

I uploaded the fix:
https://github.com/radjkarl/dataArtist/releases/tag/0.10.3b

Both lens calibration and vignetting measurement work again - a camera
calibration can be created and updated.
Would you mind to give it a try?

thanks,
karl

**Comment by willhobbs** [comment]
It seems to be working now. Thanks!

I noticed that the Perspective Correction menu has changed slightly, and I can't turn off manual object detection (that is, automatic perspective correction does not seem to be available). Is there a new way to run that?

Will

**Comment by radjkarl** [comment]
Hi Will,

So thats the thing - all automated device and feature detection will be
included in my new program ... it wont be free, but will make automated EL
correction fast and simple  ...

Sorry about that.
